### ISSUE TITLE
Usage of Thermocouples, RTDs and Flowmeters

### ISSUE THREAD

**Issue by michiAkaWhitey** [yaq-project/yaqd-labjack#32]
Dear Blaise,

My name is Michael Weiß and I am a mechatronics students at the university in Linz/Austria. I recently reproduced your great "yaq" work. Currently I am able to read voltage data from the Labjack T7. Now in a second step I want to read data from thermocouples, PT100/PT1000 and  flowmeters (impellers). The data acquisition together with kipling to a .csv file works. But I do not know to to setup the TOML file to achieve my goal.

TOML:
[daq]
address = "192.168.1.207"
port = 37000
loop_at_startup = true

channels.ai0 = {modbus_address = 0, range = 10.0}

Python:
import yaqc
import time

client = yaqc.Client(port=37000)

while client.measure():
    data = client.get_measured()
    print(f"AI0: {data['ai0']:.1f}V", end="\r", flush=True)
    time.sleep(0.1)

Thank  you for your help ;-)
All the best,
Michael

**Comment by untzag** [comment]
Hi Michael :wave:, thanks for your careful question.

I myself wrestled with this problem recently in a reactor we're building. If you read the documentation carefully, you'll find that you can change the behavior of the different channels by writing to special other modbus addresses. For example, to set a given channel to be a thermocouple input you can write to the block of 9000 addresses. There isn't a lot of consistency here, you just have to read the documentation carefully and set the appropriate addresses. I think you should approach this problem by asking "how can I set channel X as a thermocouple and channel Y as a counter".

In the most recent release, v2023.2.0, there is added functionality to set these configuration addresses for sensors. See following for the config file I'm using in my instrument.

https://github.com/yaq-project/yaqd-labjack/blob/main/example-yaq-configs/labjack-sensor/landis.toml

If there's a feature you need let me know I'm sure we could add it.

**Comment by untzag** [comment]
In a pinch, you MIGHT be able to get away with using kipling to configure the device and then only using yaq to read. I'm not sure, and I think it won't be a very robust long-term solution. Might be something to play with to get started.

**Comment by michiAkaWhitey** [comment]
Hello Blaise,
Thank you for your quick answer. I really appreciate this ;-)

Currently I am able to configure the sensor in kipling an it works
![Kipling_Thermocouple](https://user-images.githubusercontent.com/50871748/224968515-e15c16cf-f862-4d60-9701-0c2204b12b2b.png)

Currently I am also familiar with the different modbus addresses 
https://labjack.com/pages/support?doc=/datasheets/t-series-datasheet/31-modbus-map-t-series-datasheet/
https://labjack.com/pages/support?doc=%2Fdatasheets%2Ft-series-datasheet%2F1411-thermocouple-t7-only-t-series-datasheet%2F

But unfortunally your example does not work if I run the command line an error appears

![image](https://user-images.githubusercontent.com/50871748/224970595-01ee5feb-d2ed-4462-b48d-d9734660e5c8.png)

I still tried different configurations, but I am not able to run the thermocouple

Which setting do I need for a minimal example (thermocouple connected to AIN0 and AIN1, Type K, Units K or C)?

**Comment by untzag** [comment]
I think you're using an out-of-date version of yaqd-labjack-sensor. I think this because it's complaining about the key `range` in config and that's no-longer a key.

Can you check `yaqd-labjack-sensor --version`?

**Comment by untzag** [comment]
> Which setting do I need for a minimal example (thermocouple connected to AIN0 and AIN1, Type K, Units K or C)?

Here's an UNTESTED config that I think does what you ask. There's a lot of details, it's hard to troubleshoot without actual hardware.

```toml
[daq]
address = "192.168.1.207"
port = 37000
loop_at_startup = true

[[daq.settings]]
comment = "ai0 differential"
modbus_address = 41000
modbus_type = "uint16"
value = 1

[[daq.settings]]
comment = "ai0 full resolution"
modbus_address = 41500
modbus_type = "uint16"
value = 12

[[daq.settings]]
comment = "temperature range"
modbus_address = 40000
modbus_type = "float32"
value = 0.1

[[daq.settings]]
comment = "ai0 thermocouple type k"
modbus_address = 9000
modbus_type = "uint32"
value = 22

[daq.channels.temperature]
modbus_address = 7000
modbus_type = "float32"
units = "K"
```
