### ISSUE TITLE
Several thermocouples - data conversion

### ISSUE THREAD

**Issue by michiAkaWhitey** [yaq-project/yaqd-labjack#36]
Hy Blaise,

After I got familiar with the concepts of TOML, Modbus as wells as your great help to run a single thermocouple I want to add more sensors. But cloning and shifting (from ai0/ai1 to ai2/ai3 - I checked the registers with the modbus map) do not work. I also found a possible reason. Could there be an issue with the data conversion? Because why are some modbus adresses printed as lists? Like the fourth and eight line?
![image](https://user-images.githubusercontent.com/50871748/232488312-544772c2-02de-4d30-9b2a-0e203d68f939.png)

Please also see my configuration file:
```toml
[daq]
address = "140.78.134.245"
port = 37000
loop_at_startup = true

# TOML configuration for thermocouple type K on ai2, with ai3 as GND
[[daq.settings]]
comment = "ai2 differential" 
modbus_address = 41003 #AIN3_NEGATIVE_CH
modbus_type = "uint16"
value = 1 # True

[[daq.settings]]
comment = "ai2 full resolution"
modbus_address = 41502 #AIN2_RESOLUTION_INDEX
modbus_type = "uint16"
value = 12 

[[daq.settings]]
comment = "voltage range"
modbus_address = 40004 # AIN2_RANGE
modbus_type = "float32"
value = 0.1 # Voltage Range

[[daq.settings]]
comment = "ai2 thermocouple type k"
modbus_address = 9004 # AIN2_EF_INDEX
modbus_type = "uint32"
value = 22 # 22: Thermocouple type K

[daq.channels.S1] # S1 individual name
modbus_address = 7004 #AIN2_READ_A
modbus_type = "float32"
value = 1 # 0=Kelvin, 1=Celsius, 2=Fahrenheit

# TOML configuration for thermocouple type K on ai0, with ai1 as GND
[[daq.settings]]
comment = "ai0 differential" 
modbus_address = 41001 #AIN1_NEGATIVE_CH
modbus_type = "uint16"
value = 1

[[daq.settings]]
comment = "ai0 full resolution"
modbus_address = 41500 #AIN0_RESOLUTION_INDEX
modbus_type = "uint16"
value = 12 # 12 means 

[[daq.settings]]
comment = "voltage range"
modbus_address = 40000 # AIN0_RANGE
modbus_type = "float32"
value = 0.1

[[daq.settings]]
comment = "ai0 thermocouple type k"
modbus_address = 9000 # AIN0_EF_INDEX
modbus_type = "uint32"
value = 22 # 22: Thermocouple type K

[daq.channels.S0] # S0 individual name
modbus_address = 7000 #AIN0_READ_A
modbus_type = "float32"
value = 1 # 0=Kelvin, 1=Celsius, 2=Fahrenheit
```
